
package MPHpages.HR_ManagerPortal;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;


public class HRManagerPortal extends javax.swing.JFrame {
    
    private final String fullName; // Add a field to store the full name
    private final String employeeID; // Add a field to store the employee ID from login page
    private final String userRole; // Add a field to store the user role
    
    /**
     * Creates new form HR/Manager Portal
     * @param fullName
     * @param employeeID
     * @param userRole
     */
    
    public HRManagerPortal(String fullName, String employeeID, String userRole) {
        this.fullName = fullName; // Store the full name
        this.employeeID = employeeID;
        this.userRole = userRole;
        initComponents();
        
        hrmngrpageheaderLBL.setText("Welcome, ADMIN " + fullName + "!");
        hrmngrpagenameLBL.setText(fullName);
        startLiveClock(); // Start the live clock
    }
    
    /**
     * Creates new form HRManagerPage
     */
    public HRManagerPortal() {
        initComponents();
        // Initialize fullName to an empty string or any default value
        this.fullName = "";
        this.employeeID = null;
        hrmngrpageheaderLBL.setText("Welcome, " + fullName + "!");
        hrmngrpagenameLBL.setText("Admin" + fullName);
        startLiveClock(); // Start the live clock
        this.userRole = null;
    }
    // Method to update the dateTime label with the current date and time
    private void updateDateTime() {
        // Get the current date and time
        LocalDateTime now = LocalDateTime.now();
        // Define a date-time formatter
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        // Format the current date and time
        String formattedDateTime = now.format(formatter);
        // Set the formatted date and time to the label
        dateTime.setText(formattedDateTime);
    }

    // Method to start the live clock using a Timer
    private void startLiveClock() {
        // Create a timer that calls updateDateTime() every 1000 milliseconds (1 second)
        Timer timer = new Timer(1000, e -> updateDateTime());
        // Start the timer
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emppagemenuPNL = new javax.swing.JPanel();
        logoutemppgPB = new javax.swing.JButton();
        iconprofileepLBL = new javax.swing.JLabel();
        hrmngrpagenameLBL = new javax.swing.JLabel();
        backtoemppagePB = new javax.swing.JButton();
        emppageheaderPNL = new javax.swing.JPanel();
        emppagelogoLBL = new javax.swing.JLabel();
        hrmngrpageheaderLBL = new javax.swing.JLabel();
        specialaccessPNL = new javax.swing.JPanel();
        dateTime = new javax.swing.JLabel();
        hrmngrattendPB = new javax.swing.JButton();
        leavemngmntPB = new javax.swing.JButton();
        hrmngrpayslipPB = new javax.swing.JButton();
        hrmngrdetPB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emppagemenuPNL.setBackground(new java.awt.Color(102, 102, 102));
        emppagemenuPNL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        emppagemenuPNL.setForeground(new java.awt.Color(51, 51, 55));

        logoutemppgPB.setBackground(new java.awt.Color(255, 51, 51));
        logoutemppgPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        logoutemppgPB.setForeground(new java.awt.Color(255, 255, 255));
        logoutemppgPB.setText("Log out");
        logoutemppgPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutemppgPBActionPerformed(evt);
            }
        });

        iconprofileepLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ADMIN 128 x 128.png"))); // NOI18N

        hrmngrpagenameLBL.setBackground(new java.awt.Color(204, 204, 204));
        hrmngrpagenameLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hrmngrpagenameLBL.setForeground(new java.awt.Color(255, 255, 255));
        hrmngrpagenameLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hrmngrpagenameLBL.setText("HRManager Admin User");
        hrmngrpagenameLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        backtoemppagePB.setBackground(new java.awt.Color(255, 51, 51));
        backtoemppagePB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        backtoemppagePB.setForeground(new java.awt.Color(255, 255, 255));
        backtoemppagePB.setText("Back");
        backtoemppagePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoemppagePBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emppagemenuPNLLayout = new javax.swing.GroupLayout(emppagemenuPNL);
        emppagemenuPNL.setLayout(emppagemenuPNLLayout);
        emppagemenuPNLLayout.setHorizontalGroup(
            emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                .addGroup(emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                        .addGroup(emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(iconprofileepLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(logoutemppgPB, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(backtoemppagePB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 29, Short.MAX_VALUE))
                    .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(hrmngrpagenameLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        emppagemenuPNLLayout.setVerticalGroup(
            emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emppagemenuPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconprofileepLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hrmngrpagenameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutemppgPB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backtoemppagePB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        emppageheaderPNL.setBackground(new java.awt.Color(102, 102, 102));
        emppageheaderPNL.setForeground(new java.awt.Color(51, 51, 55));

        emppagelogoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/MPH LOGO 90 X 50.png"))); // NOI18N

        hrmngrpageheaderLBL.setBackground(new java.awt.Color(204, 204, 204));
        hrmngrpageheaderLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        hrmngrpageheaderLBL.setForeground(new java.awt.Color(255, 255, 255));
        hrmngrpageheaderLBL.setText(" ");
        hrmngrpageheaderLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout emppageheaderPNLLayout = new javax.swing.GroupLayout(emppageheaderPNL);
        emppageheaderPNL.setLayout(emppageheaderPNLLayout);
        emppageheaderPNLLayout.setHorizontalGroup(
            emppageheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emppageheaderPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hrmngrpageheaderLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emppagelogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        emppageheaderPNLLayout.setVerticalGroup(
            emppageheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emppageheaderPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emppageheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(hrmngrpageheaderLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(emppageheaderPNLLayout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addComponent(emppagelogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        specialaccessPNL.setBackground(new java.awt.Color(102, 102, 102));
        specialaccessPNL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        specialaccessPNL.setForeground(new java.awt.Color(102, 102, 102));

        dateTime.setBackground(new java.awt.Color(255, 255, 255));
        dateTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateTime.setForeground(new java.awt.Color(255, 255, 255));
        dateTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTime.setText("DD/MM/YYYY HH:MM:00");

        javax.swing.GroupLayout specialaccessPNLLayout = new javax.swing.GroupLayout(specialaccessPNL);
        specialaccessPNL.setLayout(specialaccessPNLLayout);
        specialaccessPNLLayout.setHorizontalGroup(
            specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialaccessPNLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        specialaccessPNLLayout.setVerticalGroup(
            specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialaccessPNLLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(dateTime)
                .addContainerGap())
        );

        hrmngrattendPB.setBackground(new java.awt.Color(255, 51, 51));
        hrmngrattendPB.setFont(new java.awt.Font("Helvetica", 1, 10)); // NOI18N
        hrmngrattendPB.setForeground(new java.awt.Color(255, 255, 255));
        hrmngrattendPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ATTENDANCE 64 X 64.png"))); // NOI18N
        hrmngrattendPB.setText("Attendance Details");
        hrmngrattendPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrmngrattendPBActionPerformed(evt);
            }
        });

        leavemngmntPB.setBackground(new java.awt.Color(255, 51, 51));
        leavemngmntPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        leavemngmntPB.setForeground(new java.awt.Color(255, 255, 255));
        leavemngmntPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/REQUEST LEAVE 64 X 64.png"))); // NOI18N
        leavemngmntPB.setText("Leave Management");
        leavemngmntPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leavemngmntPBActionPerformed(evt);
            }
        });

        hrmngrpayslipPB.setBackground(new java.awt.Color(255, 51, 51));
        hrmngrpayslipPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        hrmngrpayslipPB.setForeground(new java.awt.Color(255, 255, 255));
        hrmngrpayslipPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/SALARY INFO 64 X64.png"))); // NOI18N
        hrmngrpayslipPB.setText("Payslip Details");
        hrmngrpayslipPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrmngrpayslipPBActionPerformed(evt);
            }
        });

        hrmngrdetPB.setBackground(new java.awt.Color(255, 51, 51));
        hrmngrdetPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        hrmngrdetPB.setForeground(new java.awt.Color(255, 255, 255));
        hrmngrdetPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/DETAILS 64 X 64.png"))); // NOI18N
        hrmngrdetPB.setText("Employee Details");
        hrmngrdetPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrmngrdetPBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(280, 280, 280)
                .addComponent(hrmngrdetPB, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(hrmngrattendPB, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(emppagemenuPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(specialaccessPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(emppageheaderPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(leavemngmntPB, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(80, 80, 80)
                            .addComponent(hrmngrpayslipPB, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hrmngrdetPB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrmngrattendPB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(286, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(emppagemenuPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, 0)
                            .addComponent(specialaccessPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(emppageheaderPNL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(220, 220, 220)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(leavemngmntPB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hrmngrpayslipPB, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutemppgPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutemppgPBActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Close Accounting Portal
            this.dispose();
            // Open Employee Portal
            MPHpages.ALoginPage loginPage = new MPHpages.ALoginPage();
            loginPage.setVisible(true);
        }

    }//GEN-LAST:event_logoutemppgPBActionPerformed

    private void backtoemppagePBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoemppagePBActionPerformed
        // Create an instance of EmployeePortal
        MPHpages.EmployeePortal.EmployeePortal employeePortal = new MPHpages.EmployeePortal.EmployeePortal(fullName, employeeID, userRole);
        // Center the EmployeePortal
        employeePortal.setLocationRelativeTo(null);
        // Make the EmployeePortal visible
        employeePortal.setVisible(true);
        // Close the current HRManager Portal
        this.dispose();
    }//GEN-LAST:event_backtoemppagePBActionPerformed

    private void leavemngmntPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leavemngmntPBActionPerformed
        // Opens Employee Leave Management Page
        LeaveManagement leaveManagement = new LeaveManagement(fullName, employeeID, userRole);
        leaveManagement.setLocationRelativeTo(null); // Center the Leave Management Page for Admin Use
        leaveManagement.setVisible(true);
        this.dispose(); // Close the current HRManager Portal Page 
    }//GEN-LAST:event_leavemngmntPBActionPerformed

    private void hrmngrpayslipPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrmngrpayslipPBActionPerformed
        // Opens Employee Payroll Information Page
        PayInfoHRManager payInfoHRManager = new PayInfoHRManager(fullName, employeeID, userRole);
        payInfoHRManager.setLocationRelativeTo(null); // Center the PayInfo Page for Admin Use
        payInfoHRManager.setVisible(true);
        this.dispose(); // Close the current HRManager Portal Page 
    }//GEN-LAST:event_hrmngrpayslipPBActionPerformed

    private void hrmngrdetPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrmngrdetPBActionPerformed
        // Opens employee details page with basic pay information
        EmployeeDetailsHR employeeDetails = new EmployeeDetailsHR(fullName, employeeID, userRole);
        employeeDetails.setLocationRelativeTo(null); // Center the Employee Details Page for Admin Use
        employeeDetails.setVisible(true);
        this.dispose(); // Close the current HRManager Portal Page 
    }//GEN-LAST:event_hrmngrdetPBActionPerformed

    private void hrmngrattendPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrmngrattendPBActionPerformed
        // Opens Employee Attendance page 
        AttendancePageHRManager attendancePage = new AttendancePageHRManager(fullName, employeeID, userRole);
        attendancePage.setLocationRelativeTo(null); // Center the Attendance Page for Admin Use
        attendancePage.setVisible(true);
        this.dispose(); // Close the current HRManager Portal Page 
    }//GEN-LAST:event_hrmngrattendPBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRManagerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRManagerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRManagerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRManagerPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRManagerPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backtoemppagePB;
    private javax.swing.JLabel dateTime;
    private javax.swing.JPanel emppageheaderPNL;
    private javax.swing.JLabel emppagelogoLBL;
    private javax.swing.JPanel emppagemenuPNL;
    private javax.swing.JButton hrmngrattendPB;
    private javax.swing.JButton hrmngrdetPB;
    private javax.swing.JLabel hrmngrpageheaderLBL;
    private javax.swing.JLabel hrmngrpagenameLBL;
    private javax.swing.JButton hrmngrpayslipPB;
    private javax.swing.JLabel iconprofileepLBL;
    private javax.swing.JButton leavemngmntPB;
    private javax.swing.JButton logoutemppgPB;
    private javax.swing.JPanel specialaccessPNL;
    // End of variables declaration//GEN-END:variables
}
