

package MPHpages.AccountingPortal;

import MPHpages.HR_ManagerPortal.EmployeeDetailsHR;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class AccountingPortal extends javax.swing.JFrame {
   
    private final String fullName; // Add a field to store the full name
    private final String employeeID; // Add a field to store the employee ID from login page
    private final String userRole; // Add a field to store the user role
    
    
    /**
     * Creates new form Accounting Portal
     * @param fullName
     * @param employeeID
     * @param userRole
     */
    
    public AccountingPortal(String fullName, String employeeID, String userRole) {
        this.fullName = fullName; // Store the full name
        this.employeeID = employeeID; // Add a field to store the employee ID from login page
        this.userRole = userRole; // Add a field to store the user role
        initComponents();
        
        accpageheaderLBL.setText("Welcome, ADMIN " + fullName + "!");
        accpagenameLBL.setText(fullName);
        startLiveClock(); // Start the live clock
    }
    
    public AccountingPortal() {
        initComponents(); // Call the initComponents method to initialize components
        // Initialize fullName to an empty string or any default value
        this.fullName = "";
        // This will center the window after the components have been initialized and packed
        setLocationRelativeTo(null);
        this.employeeID = null;
        this.userRole = null;
        
        backtoemppagePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoemppagePBActionPerformed(evt);
            }
        });
        startLiveClock(); // Start the live clock
        
    }
    
    // Method to update the dateTime label with the current date and time
    private void updateDateTime() {
        // Get the current date and time
        LocalDateTime now = LocalDateTime.now();
        // Define a date-time formatter
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        // Format the current date and time
        String formattedDateTime = now.format(formatter);
        // Set the formatted date and time to the label
        dateTime.setText(formattedDateTime);
    }

    // Method to start the live clock using a Timer
    private void startLiveClock() {
        // Create a timer that calls updateDateTime() every 1000 milliseconds (1 second)
        Timer timer = new Timer(1000, e -> updateDateTime());
        // Start the timer
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emppagemainPNL = new javax.swing.JPanel();
        emppagemenuPNL = new javax.swing.JPanel();
        logoutemppgPB = new javax.swing.JButton();
        iconprofileepLBL = new javax.swing.JLabel();
        accpagenameLBL = new javax.swing.JLabel();
        backtoemppagePB = new javax.swing.JButton();
        emppageheaderPNL = new javax.swing.JPanel();
        emppagelogoLBL = new javax.swing.JLabel();
        accpageheaderLBL = new javax.swing.JLabel();
        specialaccessPNL = new javax.swing.JPanel();
        dateTime = new javax.swing.JLabel();
        empdetailsadminPB = new javax.swing.JButton();
        attendanceadminPB = new javax.swing.JButton();
        payslipinfoPB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emppagemainPNL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emppagemainPNL.setLayout(null);

        emppagemenuPNL.setBackground(new java.awt.Color(102, 102, 102));
        emppagemenuPNL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        emppagemenuPNL.setForeground(new java.awt.Color(51, 51, 55));

        logoutemppgPB.setBackground(new java.awt.Color(255, 51, 51));
        logoutemppgPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        logoutemppgPB.setForeground(new java.awt.Color(255, 255, 255));
        logoutemppgPB.setText("Log out");
        logoutemppgPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutemppgPBActionPerformed(evt);
            }
        });

        iconprofileepLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ADMIN 128 x 128.png"))); // NOI18N

        accpagenameLBL.setBackground(new java.awt.Color(204, 204, 204));
        accpagenameLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        accpagenameLBL.setForeground(new java.awt.Color(255, 255, 255));
        accpagenameLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        accpagenameLBL.setText("Accounting Admin User");
        accpagenameLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        backtoemppagePB.setBackground(new java.awt.Color(255, 51, 51));
        backtoemppagePB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        backtoemppagePB.setForeground(new java.awt.Color(255, 255, 255));
        backtoemppagePB.setText("Back");
        backtoemppagePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoemppagePBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emppagemenuPNLLayout = new javax.swing.GroupLayout(emppagemenuPNL);
        emppagemenuPNL.setLayout(emppagemenuPNLLayout);
        emppagemenuPNLLayout.setHorizontalGroup(
            emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                .addGroup(emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                        .addGroup(emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(iconprofileepLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(logoutemppgPB, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(backtoemppagePB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(accpagenameLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        emppagemenuPNLLayout.setVerticalGroup(
            emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emppagemenuPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconprofileepLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accpagenameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutemppgPB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backtoemppagePB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        accpagenameLBL.getAccessibleContext().setAccessibleName("");

        emppagemainPNL.add(emppagemenuPNL);
        emppagemenuPNL.setBounds(0, 0, 200, 360);

        emppageheaderPNL.setBackground(new java.awt.Color(102, 102, 102));
        emppageheaderPNL.setForeground(new java.awt.Color(51, 51, 55));

        emppagelogoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/MPH LOGO 90 X 50.png"))); // NOI18N

        accpageheaderLBL.setBackground(new java.awt.Color(204, 204, 204));
        accpageheaderLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        accpageheaderLBL.setForeground(new java.awt.Color(255, 255, 255));
        accpageheaderLBL.setText(" ");
        accpageheaderLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout emppageheaderPNLLayout = new javax.swing.GroupLayout(emppageheaderPNL);
        emppageheaderPNL.setLayout(emppageheaderPNLLayout);
        emppageheaderPNLLayout.setHorizontalGroup(
            emppageheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emppageheaderPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(accpageheaderLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emppagelogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        emppageheaderPNLLayout.setVerticalGroup(
            emppageheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emppageheaderPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emppageheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(accpageheaderLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(emppageheaderPNLLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(emppagelogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        emppagemainPNL.add(emppageheaderPNL);
        emppageheaderPNL.setBounds(200, 0, 730, 60);

        specialaccessPNL.setBackground(new java.awt.Color(102, 102, 102));
        specialaccessPNL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        specialaccessPNL.setForeground(new java.awt.Color(102, 102, 102));

        dateTime.setBackground(new java.awt.Color(255, 255, 255));
        dateTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateTime.setForeground(new java.awt.Color(255, 255, 255));
        dateTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTime.setText("DD/MM/YYYY HH:MM:00");

        javax.swing.GroupLayout specialaccessPNLLayout = new javax.swing.GroupLayout(specialaccessPNL);
        specialaccessPNL.setLayout(specialaccessPNLLayout);
        specialaccessPNLLayout.setHorizontalGroup(
            specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialaccessPNLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        specialaccessPNLLayout.setVerticalGroup(
            specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialaccessPNLLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addComponent(dateTime)
                .addContainerGap())
        );

        emppagemainPNL.add(specialaccessPNL);
        specialaccessPNL.setBounds(0, 360, 200, 150);

        empdetailsadminPB.setBackground(new java.awt.Color(255, 51, 51));
        empdetailsadminPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        empdetailsadminPB.setForeground(new java.awt.Color(255, 255, 255));
        empdetailsadminPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/DETAILS 64 X 64.png"))); // NOI18N
        empdetailsadminPB.setText("Employee Details");
        empdetailsadminPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empdetailsadminPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(empdetailsadminPB);
        empdetailsadminPB.setBounds(280, 100, 220, 130);

        attendanceadminPB.setBackground(new java.awt.Color(255, 51, 51));
        attendanceadminPB.setFont(new java.awt.Font("Helvetica", 1, 10)); // NOI18N
        attendanceadminPB.setForeground(new java.awt.Color(255, 255, 255));
        attendanceadminPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ATTENDANCE 64 X 64.png"))); // NOI18N
        attendanceadminPB.setText("Attendance Details");
        attendanceadminPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceadminPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(attendanceadminPB);
        attendanceadminPB.setBounds(580, 100, 200, 130);

        payslipinfoPB.setBackground(new java.awt.Color(255, 51, 51));
        payslipinfoPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        payslipinfoPB.setForeground(new java.awt.Color(255, 255, 255));
        payslipinfoPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/SALARY INFO 64 X64.png"))); // NOI18N
        payslipinfoPB.setText("Payslip Information");
        payslipinfoPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payslipinfoPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(payslipinfoPB);
        payslipinfoPB.setBounds(430, 280, 210, 130);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(emppagemainPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emppagemainPNL, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutemppgPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutemppgPBActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Close Accounting Portal
            this.dispose();
            // Open Employee Portal
            MPHpages.ALoginPage loginPage = new MPHpages.ALoginPage();
            loginPage.setVisible(true);
        }
  
    }//GEN-LAST:event_logoutemppgPBActionPerformed

    private void empdetailsadminPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empdetailsadminPBActionPerformed
         // Opens employee details page with basic pay information
        EmployeeDetailsACC employeedetailsACC = new EmployeeDetailsACC(fullName, employeeID, userRole);
        employeedetailsACC.setLocationRelativeTo(null); // Center the Employee Details Page for Admin Use
        employeedetailsACC.setVisible(true);
        this.dispose(); // Close the current Accounting Portal Page 
    }//GEN-LAST:event_empdetailsadminPBActionPerformed

    private void payslipinfoPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payslipinfoPBActionPerformed
        // opens payslip information for all employees
        PayInfoACC payInfo = new PayInfoACC(fullName, employeeID, userRole);
        payInfo.setLocationRelativeTo(null);
        payInfo.setVisible(true);
        this.dispose(); // Close the current Accounting Portal Page 
    }//GEN-LAST:event_payslipinfoPBActionPerformed

    private void backtoemppagePBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoemppagePBActionPerformed
        // Create an instance of EmployeePortal
        MPHpages.EmployeePortal.EmployeePortal employeePortal = new MPHpages.EmployeePortal.EmployeePortal(fullName, employeeID, userRole);
        // Center the EmployeePortal
        employeePortal.setLocationRelativeTo(null);
        // Make the EmployeePortal visible
        employeePortal.setVisible(true);
        // Close the current Acounting Portal
        this.dispose();

    }//GEN-LAST:event_backtoemppagePBActionPerformed

    private void attendanceadminPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceadminPBActionPerformed
        // Opens Employee Attendance page 
        AttendancePageACC attendancePageACC = new  AttendancePageACC(fullName, employeeID, userRole);
        attendancePageACC.setLocationRelativeTo(null); // Center the Attendance Page for Admin Use
        attendancePageACC.setVisible(true);
        this.dispose(); // Close the current Accounting Portal Page 
    }//GEN-LAST:event_attendanceadminPBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeDetailsHR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AccountingPortal().setVisible(true);
        });
    }
   

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accpageheaderLBL;
    private javax.swing.JLabel accpagenameLBL;
    private javax.swing.JButton attendanceadminPB;
    private javax.swing.JButton backtoemppagePB;
    private javax.swing.JLabel dateTime;
    private javax.swing.JButton empdetailsadminPB;
    private javax.swing.JPanel emppageheaderPNL;
    private javax.swing.JLabel emppagelogoLBL;
    private javax.swing.JPanel emppagemainPNL;
    private javax.swing.JPanel emppagemenuPNL;
    private javax.swing.JLabel iconprofileepLBL;
    private javax.swing.JButton logoutemppgPB;
    private javax.swing.JButton payslipinfoPB;
    private javax.swing.JPanel specialaccessPNL;
    // End of variables declaration//GEN-END:variables
}
