/*

FEATURES:
- Buttons that link to other pages
- Live date and time
- Only shows admin access buttons for sepcific users 
*/

package MPHpages.EmployeePortal;

import MPHpages.ALoginPage;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.Timer;

public class EmployeePortal extends javax.swing.JFrame {
   
    private final String fullName; // Add a field to store the full name
    private final String employeeID; // Add a field to store the employee ID
    private final String userRole; // Add a field to store the user role
    
    // Components for buttons to be hidden
    // private JButton hrmanagerpagePB;
   // private JButton accountingpagePB;
   
    /**
     * Creates new form EmployeePortal
     * @param fullName
     * @param employeeID
     * @param userRole
     */
    public EmployeePortal(String fullName, String employeeID, String userRole) {
        initComponents();
        this.fullName = fullName;
        this.employeeID = employeeID;
        this.userRole = userRole;
        employeepageheaderLBL.setText("Welcome, EMPLOYEE " + fullName + "!");
        employeepagenameLBL.setText(fullName);
        startLiveClock(); // Start the live clock
        
        // Initialize additional components
        initializeAdditionalComponents();
        
        // Hide buttons based on user role
        configureButtonsForUserRole();
    }

    public EmployeePortal() {
        initComponents();
        this.fullName = "";
        this.employeeID = null;
        this.userRole = ""; // Initialize to an empty string or any default value

        // Initialize additional components
        initializeAdditionalComponents();
    }
    
     private void initializeAdditionalComponents() {
        startLiveClock(); // Start the live clock

    // Ensure the layout manager of your panel or frame allows for manual positioning
    getContentPane().setLayout(null);
    }
    
     private void configureButtonsForUserRole() {
        if (userRole == null) return;

        switch (userRole.toUpperCase()) {
        case "EMPLOYEE":
            hrmanagerpagePB.setVisible(false);
            accountingpagePB.setVisible(false);
            userrolesaccessLBL.setVisible(false);
            break;
        case "HR/MANAGER":
            accountingpagePB.setVisible(false);
            break;
        case "ACCOUNTING":
            hrmanagerpagePB.setVisible(false);
            break;
        default:
            // If userRole is not recognized, you can handle this as needed
            hrmanagerpagePB.setVisible(false);
            accountingpagePB.setVisible(false);
            break;
        }
    }

      // Method to update the dateTime label with the current date and time
    private void updateDateTime() {
        // Get the current date and time
        LocalDateTime now = LocalDateTime.now();
        // Define a date-time formatter
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        // Format the current date and time
        String formattedDateTime = now.format(formatter);
        // Set the formatted date and time to the label
        dateTime.setText(formattedDateTime);
    }

    // Method to start the live clock using a Timer
    private void startLiveClock() {
        // Create a timer that calls updateDateTime() every 1000 milliseconds (1 second)
        Timer timer = new Timer(1000, e -> updateDateTime());
        // Start the timer
        timer.start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emppagemainPNL = new javax.swing.JPanel();
        emppagemenuPNL = new javax.swing.JPanel();
        logoutemppgPB = new javax.swing.JButton();
        iconprofileepLBL = new javax.swing.JLabel();
        employeepagenameLBL = new javax.swing.JLabel();
        emppageheaderPNL = new javax.swing.JPanel();
        emppagelogoLBL = new javax.swing.JLabel();
        employeepageheaderLBL = new javax.swing.JLabel();
        specialaccessPNL = new javax.swing.JPanel();
        userrolesaccessLBL = new javax.swing.JLabel();
        hrmanagerpagePB = new javax.swing.JButton();
        accountingpagePB = new javax.swing.JButton();
        dateTime = new javax.swing.JLabel();
        aboutPB = new javax.swing.JButton();
        personaldetPB = new javax.swing.JButton();
        attendanceemppgPB = new javax.swing.JButton();
        payrollemppgPB = new javax.swing.JButton();
        requestleaveemppgPB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emppagemainPNL.setBackground(new java.awt.Color(204, 204, 204));
        emppagemainPNL.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        emppagemainPNL.setLayout(null);

        emppagemenuPNL.setBackground(new java.awt.Color(102, 102, 102));
        emppagemenuPNL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        emppagemenuPNL.setForeground(new java.awt.Color(51, 51, 55));

        logoutemppgPB.setBackground(new java.awt.Color(255, 51, 51));
        logoutemppgPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        logoutemppgPB.setForeground(new java.awt.Color(255, 255, 255));
        logoutemppgPB.setText("Log out");
        logoutemppgPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutemppgPBActionPerformed(evt);
            }
        });

        iconprofileepLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/USER 128 X 128.png"))); // NOI18N

        employeepagenameLBL.setBackground(new java.awt.Color(51, 51, 51));
        employeepagenameLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeepagenameLBL.setForeground(new java.awt.Color(255, 255, 255));
        employeepagenameLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employeepagenameLBL.setText("Employee User");
        employeepagenameLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout emppagemenuPNLLayout = new javax.swing.GroupLayout(emppagemenuPNL);
        emppagemenuPNL.setLayout(emppagemenuPNLLayout);
        emppagemenuPNLLayout.setHorizontalGroup(
            emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                .addGroup(emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                        .addGroup(emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(iconprofileepLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(logoutemppgPB, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addGroup(emppagemenuPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(employeepagenameLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        emppagemenuPNLLayout.setVerticalGroup(
            emppagemenuPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emppagemenuPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconprofileepLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(employeepagenameLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logoutemppgPB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        employeepagenameLBL.getAccessibleContext().setAccessibleName("");

        emppagemainPNL.add(emppagemenuPNL);
        emppagemenuPNL.setBounds(0, 0, 200, 280);

        emppageheaderPNL.setBackground(new java.awt.Color(102, 102, 102));
        emppageheaderPNL.setForeground(new java.awt.Color(51, 51, 55));

        emppagelogoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/MPH LOGO 90 X 50.png"))); // NOI18N

        employeepageheaderLBL.setBackground(new java.awt.Color(204, 204, 204));
        employeepageheaderLBL.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        employeepageheaderLBL.setForeground(new java.awt.Color(255, 255, 255));
        employeepageheaderLBL.setText(" ");
        employeepageheaderLBL.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout emppageheaderPNLLayout = new javax.swing.GroupLayout(emppageheaderPNL);
        emppageheaderPNL.setLayout(emppageheaderPNLLayout);
        emppageheaderPNLLayout.setHorizontalGroup(
            emppageheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emppageheaderPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(employeepageheaderLBL, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emppagelogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        emppageheaderPNLLayout.setVerticalGroup(
            emppageheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emppageheaderPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emppageheaderPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(employeepageheaderLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(emppageheaderPNLLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(emppagelogoLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        emppagemainPNL.add(emppageheaderPNL);
        emppageheaderPNL.setBounds(200, 0, 730, 60);

        specialaccessPNL.setBackground(new java.awt.Color(102, 102, 102));
        specialaccessPNL.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        specialaccessPNL.setForeground(new java.awt.Color(102, 102, 102));

        userrolesaccessLBL.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userrolesaccessLBL.setForeground(new java.awt.Color(255, 255, 255));
        userrolesaccessLBL.setText("ADMIN ACCESS");

        hrmanagerpagePB.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        hrmanagerpagePB.setText("HR/MANAGER");
        hrmanagerpagePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hrmanagerpagePBActionPerformed(evt);
            }
        });

        accountingpagePB.setFont(new java.awt.Font("Helvetica", 0, 14)); // NOI18N
        accountingpagePB.setText("ACCOUNTING");
        accountingpagePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountingpagePBActionPerformed(evt);
            }
        });

        dateTime.setBackground(new java.awt.Color(255, 255, 255));
        dateTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dateTime.setForeground(new java.awt.Color(255, 255, 255));
        dateTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dateTime.setText("DD/MM/YYYY HH:MM:00");

        javax.swing.GroupLayout specialaccessPNLLayout = new javax.swing.GroupLayout(specialaccessPNL);
        specialaccessPNL.setLayout(specialaccessPNLLayout);
        specialaccessPNLLayout.setHorizontalGroup(
            specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialaccessPNLLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialaccessPNLLayout.createSequentialGroup()
                        .addGroup(specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accountingpagePB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hrmanagerpagePB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userrolesaccessLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, specialaccessPNLLayout.createSequentialGroup()
                        .addComponent(dateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        specialaccessPNLLayout.setVerticalGroup(
            specialaccessPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(specialaccessPNLLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(userrolesaccessLBL)
                .addGap(27, 27, 27)
                .addComponent(hrmanagerpagePB, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(accountingpagePB, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(dateTime)
                .addContainerGap())
        );

        emppagemainPNL.add(specialaccessPNL);
        specialaccessPNL.setBounds(0, 280, 200, 230);

        aboutPB.setBackground(new java.awt.Color(255, 51, 51));
        aboutPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        aboutPB.setForeground(new java.awt.Color(255, 255, 255));
        aboutPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/COMPANY 100 X 100.png"))); // NOI18N
        aboutPB.setText("About");
        aboutPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(aboutPB);
        aboutPB.setBounds(250, 100, 176, 126);

        personaldetPB.setBackground(new java.awt.Color(255, 51, 51));
        personaldetPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        personaldetPB.setForeground(new java.awt.Color(255, 255, 255));
        personaldetPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/DETAILS 64 X 64.png"))); // NOI18N
        personaldetPB.setText("View Details");
        personaldetPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personaldetPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(personaldetPB);
        personaldetPB.setBounds(470, 100, 176, 126);

        attendanceemppgPB.setBackground(new java.awt.Color(255, 51, 51));
        attendanceemppgPB.setFont(new java.awt.Font("Helvetica", 1, 10)); // NOI18N
        attendanceemppgPB.setForeground(new java.awt.Color(255, 255, 255));
        attendanceemppgPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/ATTENDANCE 64 X 64.png"))); // NOI18N
        attendanceemppgPB.setText("View Attendance");
        attendanceemppgPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceemppgPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(attendanceemppgPB);
        attendanceemppgPB.setBounds(690, 100, 190, 126);

        payrollemppgPB.setBackground(new java.awt.Color(255, 51, 51));
        payrollemppgPB.setFont(new java.awt.Font("Helvetica", 1, 12)); // NOI18N
        payrollemppgPB.setForeground(new java.awt.Color(255, 255, 255));
        payrollemppgPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/PAYROLL 64 X 64.png"))); // NOI18N
        payrollemppgPB.setText("View Payroll");
        payrollemppgPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payrollemppgPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(payrollemppgPB);
        payrollemppgPB.setBounds(330, 270, 176, 126);

        requestleaveemppgPB.setBackground(new java.awt.Color(255, 51, 51));
        requestleaveemppgPB.setFont(new java.awt.Font("Helvetica", 1, 10)); // NOI18N
        requestleaveemppgPB.setForeground(new java.awt.Color(255, 255, 255));
        requestleaveemppgPB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/media/REQUEST LEAVE 64 X 64.png"))); // NOI18N
        requestleaveemppgPB.setText("Request Leave");
        requestleaveemppgPB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestleaveemppgPBActionPerformed(evt);
            }
        });
        emppagemainPNL.add(requestleaveemppgPB);
        requestleaveemppgPB.setBounds(590, 270, 176, 126);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(emppagemainPNL, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(emppagemainPNL, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutemppgPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutemppgPBActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Confirm Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            // Close EmployeePortal
            this.dispose();
            // Open LoginPage
            ALoginPage loginPage = new ALoginPage();
            loginPage.setVisible(true);
        }
  
    }//GEN-LAST:event_logoutemppgPBActionPerformed

    private void hrmanagerpagePBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hrmanagerpagePBActionPerformed
        // Create an instance to HRManager page
        MPHpages.HR_ManagerPortal.HRManagerPortal hrmanagerPage = new MPHpages.HR_ManagerPortal.HRManagerPortal(fullName, employeeID, userRole);
        hrmanagerPage.setLocationRelativeTo(null); //Center the HRManager Portal
        hrmanagerPage.setVisible(true); // Set the HRManagerPortal to be visible
        this.dispose();// Close the current EmployeePortal
    }//GEN-LAST:event_hrmanagerpagePBActionPerformed

    private void aboutPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutPBActionPerformed
        // Redirect to AboutPage
        AboutPage aboutPage = new AboutPage(fullName, employeeID, userRole);
        aboutPage.setLocationRelativeTo(null); // Center the AboutPage
        aboutPage.setVisible(true); // Set the About Page to be visible
        this.dispose(); // Close the current EmployeePortal
    }//GEN-LAST:event_aboutPBActionPerformed

    private void accountingpagePBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountingpagePBActionPerformed
        // Create an instance to accountingpage
        MPHpages.AccountingPortal.AccountingPortal accountingPage = new MPHpages.AccountingPortal.AccountingPortal(fullName, employeeID, userRole);
        accountingPage.setLocationRelativeTo(null); //Center the AccountingPortal
        accountingPage.setVisible(true); // Set the AccountingPortal to be visible
        this.dispose();// Close the current EmployeePortal
    }//GEN-LAST:event_accountingpagePBActionPerformed

    private void personaldetPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personaldetPBActionPerformed
        // Redirect to Personal Details Page
        PersonalDetailsPage personaldetailsPage = new PersonalDetailsPage(fullName, employeeID, userRole);
        personaldetailsPage.setLocationRelativeTo(null); // Center the Personal Details Page
        personaldetailsPage.setVisible(true); // Set the Personal Details Page to be visible
        this.dispose(); // Close the current EmployeePortal
    }//GEN-LAST:event_personaldetPBActionPerformed

    private void attendanceemppgPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceemppgPBActionPerformed
        // Redirect to Attendance Page
        EmpAttendancePage attendancePage = new EmpAttendancePage(fullName, employeeID, userRole);
        attendancePage.setLocationRelativeTo(null); // Center the EmpAttendancePage
        attendancePage.setVisible(true); // Set the EmpAttendancePage to be visible
        this.dispose(); // Close the current EmployeePortal
    }//GEN-LAST:event_attendanceemppgPBActionPerformed

    private void payrollemppgPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payrollemppgPBActionPerformed
        // Redirect to Payroll Employee View Page
        PayrollPage payrollpage = new PayrollPage(fullName, employeeID,userRole);
        payrollpage.setLocationRelativeTo(null); // Center the Payroll Page
        payrollpage.setVisible(true); // Set the Payroll Page to be visible
        this.dispose(); // Close the current EmployeePortal
    }//GEN-LAST:event_payrollemppgPBActionPerformed

    private void requestleaveemppgPBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestleaveemppgPBActionPerformed
        // Redirect to Request Leave Page
        EmpRequestLeavePage empRequestLeavePage = new EmpRequestLeavePage(fullName, employeeID, userRole);
        empRequestLeavePage.setLocationRelativeTo(null); // Center the Emp Request Leave Page
        empRequestLeavePage.setVisible(true); // Set the Emp Request Leave Page to be visible
        this.dispose(); // Close the current EmployeePortal
    }//GEN-LAST:event_requestleaveemppgPBActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Metal look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Metal".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(AboutPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    
    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        EmployeePortal employeePage = new EmployeePortal();
        employeePage.setLocationRelativeTo(null); // Center the AboutPage
        employeePage.setVisible(true);
    });
    
    
    }

     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutPB;
    private javax.swing.JButton accountingpagePB;
    private javax.swing.JButton attendanceemppgPB;
    private javax.swing.JLabel dateTime;
    private javax.swing.JLabel employeepageheaderLBL;
    private javax.swing.JLabel employeepagenameLBL;
    private javax.swing.JPanel emppageheaderPNL;
    private javax.swing.JLabel emppagelogoLBL;
    private javax.swing.JPanel emppagemainPNL;
    private javax.swing.JPanel emppagemenuPNL;
    private javax.swing.JButton hrmanagerpagePB;
    private javax.swing.JLabel iconprofileepLBL;
    private javax.swing.JButton logoutemppgPB;
    private javax.swing.JButton payrollemppgPB;
    private javax.swing.JButton personaldetPB;
    private javax.swing.JButton requestleaveemppgPB;
    private javax.swing.JPanel specialaccessPNL;
    private javax.swing.JLabel userrolesaccessLBL;
    // End of variables declaration//GEN-END:variables
}
